---
title: "alndist"
author: "Yue Jiang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{alndist}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(alndist)
```

```{r}
# fs <- list.files("data", full.names = T)
# for (f in fs) load(f)
#
# fs2 <- gsub(".rda", "", list.files("data"))
# for (f in fs2) {
#   mtx <- get(f)
#   colnames(mtx)[colnames(mtx) == "*"] <- "-"
#   rownames(mtx)[rownames(mtx) == "*"] <- "-"
#   saveRDS(mtx, file.path("inst", "extdata", paste0(f, ".rds")))
# }

or <- seqinr::read.fasta(system.file("extdata/mouseOR.fasta", package="alndist"), seqtype="AA")
x <- toupper(as.character(or[[1]]))
mtx <- get_substitute_mtx("PAM250")
seq_to_idx(x, mtx)
weights <- rep(1, length(x))
two_seq_score(x, x, mtx, weights)

lst <- purrr::map(or, ~toupper(as.character(.x)))
names(lst) <- purrr::map(or, ~attr(.x, "Annot"))
dist_mtx <- pairwise_score(lst, mtx, weights)
dist_pca <- prcomp(dist_mtx, scale. = TRUE)
ggplot(as.data.frame(dist_pca$x), aes(PC1, PC2)) +
  geom_point(alpha=0.3)

long_lst <- rep(lst, 10)
names(long_lst) <- 1:length(long_lst)
long_weights <- rep(1, length(long_lst))
system.time(dist_mtx <- pairwise_score(long_lst, mtx, weights))
system.time(dist_mtx <- parallel_pairwise_score(long_lst, mtx, weights))

microbenchmark::microbenchmark(dist_mtx <- pairwise_score(lst, mtx, weights))
microbenchmark::microbenchmark(dist_mtx_p <- parallel_pairwise_score(lst, mtx, weights))

identical(dist_mtx, dist_mtx_p)
```
