# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallel_pairwise_score <- function(seqs, mtx, weight) {
    .Call(`_alndist_parallel_pairwise_score`, seqs, mtx, weight)
}

#' Helper function to convert a character vector to an integer vector of positions in substitution matrix.
#' @param x Sequence as a character vector.
#' @param mtx Substitution matrix as a numeric matrix.
#'
#' @return A integer vector converting input sequence to 0-based index in col/row names of mtx.
#'
#' @export
seq_to_idx <- function(x, mtx) {
    .Call(`_alndist_seq_to_idx`, x, mtx)
}

#' Calculate scores for two aligned sequences given a substitution matrix.
#' Optionaly weight for each position in the alignment.
#' @param x Sequence 1 as a character vector.
#' @param y Sequence 2 as a character vector. Same length as sequence 1.
#' @param mtx Substitution matrix as a numeric matrix.
#' @param weight A numeric vector specifying weights for each position in sequences 1 and 2.
#' Same length as sequences 1 and 2.
#'
#' @return A single weighted score.
#'
#' @export
two_seq_score <- function(x, y, mtx, weight) {
    .Call(`_alndist_two_seq_score`, x, y, mtx, weight)
}

#' Calculate pairwise scores for aligned sequences given a substitution matrix.
#' Optionaly weight for each position in the alignment.
#' @param seqs A list of character vectors, each represents a sequence in the alignment.
#' @param mtx Substitution matrix as a numeric matrix.
#' @param weight A numeric vector specifying weights for each position in aligned sequences.
#' Same length as sequences 1 and 2.
#'
#' @return A NumericMatrix of pairwise scores.
#'
#' @export
pairwise_score <- function(seqs, mtx, weight) {
    .Call(`_alndist_pairwise_score`, seqs, mtx, weight)
}

